### ISSUE TITLE
Experiment Settings For the FPS Measurement 

### ISSUE THREAD

**Issue by licj15** [VITA-Group/LightGaussian#11]
Dear LightGaussian Authors, 

I am interested in understanding the specifics of your FPS measurements. 
Could you please specify the device used for these measurements? 

Thank you!

**Comment by zhiwenfan** [comment]
Hi, it's the same with 3D-GS paper, an A6000 GPU.

**Comment by licj15** [comment]
Thanks for the detailed information! 
I have another minor question regarding the FPS measurement codebase: Did you use 3DGS's SIBR-based viewer, or did you opt for a manual implementation of time.time() within render.py?

**Comment by Kevin-2017** [comment]
We used a manual implementation of time.time().
