### ISSUE TITLE
questions about interactive reviewer

### ISSUE THREAD

**Issue by cv-lab-x** [VITA-Group/LightGaussian#12]
hi, thanks for your great work, how to do interactive review with your compressed model? @Kevin-2017 
Looking forward to your reply, thanks!

**Comment by Kevin-2017** [comment]
Thank you for your inquiry about the open sourcing of SH distillation. I plan to upload it by the end of this week. Sorry for the delay - I was traveling abroad recently which causes the postponement. Thank you for your patience, and I'm excited to share the work with you soon!

**Comment by Kevin-2017** [comment]
Hi thank you for your intreast!
Regarding your query about interactive review with the compressed model, it's important to note that the model, after quantization, is not directly compatible with interactive review. However, there are alternative ways to achieve this:

1. Using render.py: You can view the model through render.py. This method should allow you to visualize the model effectively.

2. Alternative Method with dequantize():
In the ./vectree/vectree.py directory, there is a dequantize() function.
You can use this function to load the compressed model.
After loading, the funciton save the model to a PLY file, which is compatible with iterative viewers.

**Comment by Kevin-2017** [comment]
I noticed the currently uploaded render.py does not directly support the model after Vectree quntization, I would update that part by Friday.

**Comment by Kevin-2017** [comment]
You could render the quantized model with `python render_video.py --load_vq` now :D
