### ISSUE TITLE
example ckpt for room scene

### ISSUE THREAD

**Issue by cfchi** [VITA-Group/LightGaussian#14]
Hello, I would like to inquire whether the example checkpoint you provided for the room scene has undergone pruning, SH distillation, and Vectree Quantization processes. 
I noticed that the point cloud size in the file is 77MB, but Table 2 in the paper indicates that the model size after Vectree Quantization is 20MB. 
Could you kindly clarify if there might be a misunderstanding on my part? 
Thank you for your assistance.

**Comment by Kevin-2017** [comment]
The extreme_saving folder the result of the Vectree Quantization process, and its size is approximately 20MB. This quantized version can be rendered using the command `python render_video.py --load_vq`

However, it's important to note that current interactive viewer does not support this quantized format directly. To accommodate this, we have implemented a function that converts the quantized data back into the .ply format. This conversion results in the 77MB file size that you observed.

**Comment by yangqing-yq** [comment]
python render_video.py --load_vq -m <model_path> but it show error "no cfg_args found in folder"
