### ISSUE TITLE
Error about quantizing 3DGS checkpoint

### ISSUE THREAD

**Issue by xuyansong99** [VITA-Group/LightGaussian#15]
Hi, I get an error when I run `vectree.py`.
> ================== Print Info ================== 
Input_feats_shape:  torch.Size([1554770, 62])
VQ_feats_shape:  torch.Size([1554770, 27])
SH_degree:  2
Quantization_ratio:  0.6
Add_important_score:  True
Codebook_size:  8192
================================================ 
IS_percent:  tensor(0.7985)
100%|██████████| 1000/1000 [01:00<00:00, 16.41it/s]

> =============== Start vector quantize ===============
100%|██████████| 190/190 [00:01<00:00, 186.61it/s]
updating: ../vectree/output/bicycle/extreme_saving/ (stored 0%)
updating: ../vectree/output/bicycle/extreme_saving/metadata.npz (deflated 12%)
updating: ../vectree/output/bicycle/extreme_saving/non_vq_feats.npz (deflated 0%)
updating: ../vectree/output/bicycle/extreme_saving/xyz.npz (deflated 0%)
updating: ../vectree/output/bicycle/extreme_saving/non_vq_mask.npz (deflated 0%)
updating: ../vectree/output/bicycle/extreme_saving/other_attribute.npz (deflated 0%)
updating: ../vectree/output/bicycle/extreme_saving/codebook.npz (deflated 0%)
updating: ../vectree/output/bicycle/extreme_saving/vq_indexs.npz (deflated 0%)
Size =  70.69165706634521  MB

> ==================== Load saved data & Dequantize ==================== 
Traceback (most recent call last):
  File "/home/zxq/MachineLearning/SLAM/3DGS/LightGaussian/vectree/vectree.py", line 224, in <module>
    vq.dequantize()
  File "/home/zxq/MachineLearning/SLAM/3DGS/LightGaussian/vectree/vectree.py", line 215, in dequantize
    write_ply_data(dequantized_feats.cpu().numpy(), self.ply_path, self.sh_dim)
  File "/home/zxq/MachineLearning/SLAM/3DGS/LightGaussian/vectree/utils.py", line 101, in write_ply_data
    elements[:] = list(map(tuple, feats))
ValueError: could not assign tuple of length 62 to structure with 41 fields.

I found that the shape of `feats` is [1554770, 62] and the dtype of  `elements` is [1554770, 41], which caused the error. Besides, `elements`dtype is defined by `dtype_full`：
```python
dtype_full = [(attribute, 'f4') for attribute in construct_list_of_attributes()] 
```
So, I'd like to know the reason why the demensions between `dtype_full` and `feats` is inconsistent.
Thanks in advance！

**Comment by Kevin-2017** [comment]
This inconsistent is likely cause by the incorrect sh degree setting. 
You might want to add argument --sh_degree 3,  if you are using the default sh_degree for 3DGS.
