### ISSUE TITLE
Errors that occur when training on the room dataset.

### ISSUE THREAD

**Issue by VerseWei** [VITA-Group/LightGaussian#16]
Great job! But I encountered a problem while retraining on the dataset in the room. Are you also using the dataset downloaded from the link you provided?
python train_densify_prune.py -s /home/wxs/3D_Recon/LightGaussian/datasets/room -m /home/wxs/3D_Recon/LightGaussian/output/room
Optimizing /home/wxs/3D_Recon/LightGaussian/output/room
Output folder: /home/wxs/3D_Recon/LightGaussian/output/room [18/01 10:09:28]
Tensorboard not available: not logging progress [18/01 10:09:28]
/home/wxs/3D_Recon/LightGaussian/datasets/room [18/01 10:09:28]
Reading camera 1/30Traceback (most recent call last):
  File "/home/wxs/3D_Recon/LightGaussian/train_densify_prune.py", line 268, in <module>
    training(
  File "/home/wxs/3D_Recon/LightGaussian/train_densify_prune.py", line 57, in training
    scene = Scene(dataset, gaussians)
  File "/home/wxs/3D_Recon/LightGaussian/scene/__init__.py", line 55, in __init__
    scene_info = sceneLoadTypeCallbacks["Colmap"](
  File "/home/wxs/3D_Recon/LightGaussian/scene/dataset_readers.py", line 179, in readColmapSceneInfo
    cam_infos_unsorted = readColmapCameras(
  File "/home/wxs/3D_Recon/LightGaussian/scene/dataset_readers.py", line 106, in readColmapCameras
    assert (
AssertionError: Colmap camera model not handled: only undistorted datasets (PINHOLE or SIMPLE_PINHOLE cameras) supported!

**Comment by Kevin-2017** [comment]
Yes, I have used the dataset from the provided link for similar training processes. I think with [Mip360](https://jonbarron.info/mipnerf360/) dataset , this error shouldn't raise.  You might want to refer to @https://github.com/graphdeco-inria/gaussian-splatting/issues/4#issuecomment-1628871550
 To better assist you, could you please provide a bit more information so I could replicate the error? For example the folder strucure of the dataset?

**Comment by FredaPeng** [comment]
same here
![image](https://github.com/VITA-Group/LightGaussian/assets/115590534/8c5cbb70-9b2b-4fd7-a616-a48549d247d7)
