### ISSUE TITLE
Hardware Requirements

### ISSUE THREAD

**Issue by cfchi** [VITA-Group/LightGaussian#19]
Hi, I'm curious about the hardware requirements for the experiment. 
I've been using  a 4090 GPU with 128GB of VRAM to run the prune_finetune.py script on the Garden dataset. 
However, I'm encountering out-of-memory errors when setting the iteration to 5000. 
What sort of hardware specifications would be necessary to achieve training quality comparable to the standards outlined in the paper?
Thanks!

**Comment by Kevin-2017** [comment]
Thank you for your question! For our experiments, we primarily used an NVIDIA A6000 GPU with 48GB of VRAM for fine-tuning. Additionally, we successfully ran experiments on the Garden dataset using an A5000 GPU with 24GB of VRAM without encountering memory issues.Feel free to share more details, and we’ll be happy to assist!
