### ISSUE TITLE
Question about importance score calculation

### ISSUE THREAD

**Issue by XuyangBai** [VITA-Group/LightGaussian#2]
Hi, thanks for sharing your great work. I have a question regarding the calculation of gaussian importance score. In your paper Eq4, what's sigma_j ? from your code I found it is the opacity of the gaussian 
```
gaussian_count[collected_id[j]]++;
important_score[collected_id[j]] += con_o.w; //opacity
```
But may I ask why did you only use opacity instead of using alpha (opacity * probability from splatted gaussian) since the latter is the real contribution of the gaussian to a specific pixel? 

BTW, there might be a mistake in paper at the begining of page 4: 
> Here, ci, αi represents the color and opacity of this point computed by a Gaussian with covariance Σ multiplied by an optimizable per-point opacity and SH color coefficients.

This sentense sounds weird because αi  is not the opacity but the weight in alpha blending, and it's not related to SH

**Comment by Kevin-2017** [comment]
2) ![Screenshot from 2023-12-05 08-28-33](https://github.com/VITA-Group/LightGaussian/assets/31030008/17269d43-4a4b-4645-a180-30fd5f4b0cd3)

**Comment by XuyangBai** [comment]
Hi @Kevin-2017 Thank you for the prompt reply and detailed experimental results. Just another question out of curiosity, have you tried to prune the gaussian in a purely random way? I guess that may also be a good baseline because all the heuristic ways we design might have some bias that causes irreversible harm to 3DGS even with your co-adaption?

**Comment by Kevin-2017** [comment]
Hi @XuyangBai, thank you for the idea!! I think we could try this after the Distillation module is updated (Which I think should be within 3 days).
