### ISSUE TITLE
How to get the Global Significant Score？

### ISSUE THREAD

**Issue by Sunyike11** [VITA-Group/LightGaussian#26]
I want to modify diff-gaussian-rasterization. How to get the Global Significant Score？

**Comment by Kevin-2017** [comment]
Here is an example for the global significant score [prune.py](https://github.com/VITA-Group/LightGaussian/blob/6676b983e77baadd909effc56a6aaadafa964dcc/prune.py#L133
) The count_render function returns several parameters, one of which is important_score, representing the Global Significant Score.


Feel free to take a look, and let me know if you have any further questions!

**Comment by Sunyike11** [comment]
Thank you so much for your reply！I’m finished successfully!
