### ISSUE TITLE
How to view?

### ISSUE THREAD

**Issue by wcjj1236** [VITA-Group/LightGaussian#28]
Hey, could you give me some tips about how to reconstruct the 3DGS model from the compressed file and view it in SIBR viewer?

**Comment by Kevin-2017** [comment]
Hi wcjj1236, thank you for your interest in our work. Currently, the compressed file is not supported in the SIBR viewer. You can either decompress the quantized model or use python render_video.py --load_vq to render it. For more details, please refer to #12.
