### ISSUE TITLE
what is teacher_model in distill_train.py?how can i get teacher_model when i use own data?

### ISSUE THREAD

**Issue by smart4654154** [VITA-Group/LightGaussian#34]
thank you very much

**Comment by TimenoLong** [comment]
Have you solved this problem？

**Comment by seulqxq** [comment]
Same.

**Comment by Kevin-2017** [comment]
You could use the checkpoint from either the original 3dgs or the pruned 3dgs :D

**Comment by Kevin-2017** [comment]
Closing this issue as it seems solved and there’s no further discussion. Feel free to reopen or start a new issue if needed.
