### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by TacoAndCheese** [VITA-Group/LightGaussian#39]
Hey, can I ask why this error occur?

![gauss](https://github.com/user-attachments/assets/4a1e3bb4-431a-4ad7-bc58-94522fd2774c)

**Comment by Kevin-2017** [comment]
We've made modifications to the rasterizer. To incorporate these changes, please reinstall the compress-diff-gaussian-rasterization package using the following command: pip install submodules/compress-diff-gaussian-rasterization. This should resolve the issue. However, I recommend setting up a new conda environment to avoid any conflicts with the original 3dgs.
Additionally, ensure that your submodules are updated by running: git submodule update --init --recursive. :D

<img width="802" alt="image" src="https://github.com/user-attachments/assets/c3a6bfa2-6bc9-4baf-b583-dc7489cc0bba">
<img width="806" alt="image" src="https://github.com/user-attachments/assets/7e61f08b-fe74-4870-a899-73a08ac7dd86">

**Comment by Kevin-2017** [comment]
Closing this issue as it seems solved and there’s no further discussion. Feel free to reopen or start a new issue if needed.
