### ISSUE TITLE
Getting error when trying to run run.sh

### ISSUE THREAD

**Issue by Saptarshi666** [VITA-Group/LightGaussian#42]
I am getting the following error when i try to run the LightGaussian tutorial:                                                                                                               Optimizing output/exp_001/tandt/train
Quantized Params:  ['sh', 'dc', 'rot', 'scale'] [05/11 15:12:15]
Output folder: output/exp_001/tandt/train [05/11 15:12:15]
Tensorboard not available: not logging progress [05/11 15:12:15]
Traceback (most recent call last):
  File "train_kmeans.py", line 410, in <module>
    args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args)
  File "train_kmeans.py", line 49, in training
    scene = Scene(dataset, gaussians)
  File "/home/saptarshi/VSCodeProjects/compact3d/gaussian-splatting/scene/__init__.py", line 49, in __init__
    scene_info = sceneLoadTypeCallbacks["Colmap"](args.source_path, args.images, args.eval)
TypeError: readColmapSceneInfo() missing 2 required positional arguments: 'eval' and 'train_test_exp'

**Comment by Kevin-2017** [comment]
Thank you for your interest in our work!

It seems like you might be running https://github.com/UCDvision/compact3d instead of LightGaussian. Compact3D is also an awsome 3D-GS compression project. Perhaps you could raise your question in their issue tracker for more specific guidance
