### ISSUE TITLE
 syntax error near unexpected token `done'?

### ISSUE THREAD

**Issue by CultureAddiction** [VITA-Group/LightGaussian#43]
Just typed command below, according to your readme.

> (lightgaussian) gpuadmin@sg6:/data_ssd/YBS/LightGaussian$ bash scripts/run_train_densify_prune.sh
> GPU 0 is available. Starting train_densify_prune.py with dataset 'bicycle', prune_percent '0.6', prune_type 'v_important_score', prune_decay '0.6', and v_pow '0.1' on port 6035
> scripts/run_train_densify_prune.sh: line 89: syntax error near unexpected token `done'
> scripts/run_train_densify_prune.sh: line 89: `done'
> 
> 

Will this be a problem?

**Comment by Kevin-2017** [comment]
Thank you for the feedback! There was an extra `done `and I have just updated it.
