### ISSUE TITLE
Request an example

### ISSUE THREAD

**Issue by ALI-P48** [VITA-Group/LightGaussian#5]
Hi there, a newbie here.

I am so impressed with your excelent work.

I was wondering if i can get an example model which is compressed with your method so i can test it on Unity and see what FPS i can get with runtime unity render? That would be appreciated.

**Comment by kairunwen** [comment]
The point_cloud.ply in the link corresponds to the pruned_distilled_quantized.ply of the room scene.
https://drive.google.com/drive/folders/1yJeVLQUjYR4cnROOCYuL3o4bXi9atrYH?usp=sharing

**Comment by kairunwen** [comment]
Please check out the readme for more details.
