### ISSUE TITLE
imp_score.npz ?

### ISSUE THREAD

**Issue by zhouilu** [VITA-Group/LightGaussian#6]
Where is this file saved?

**Comment by kairunwen** [comment]
![Snipaste_2023-12-15_12-49-42](https://github.com/VITA-Group/LightGaussian/assets/65280630/1e381f12-1022-4e7d-9065-d3067d92d12d)

**Comment by kairunwen** [comment]
We will upload the codes for saving imp_score.npz within 3 days.

**Comment by Kevin-2017** [comment]
@zhouilu The codes for save imp_score.npz is updated. You could either mannualy save it with utils/save_imp_score.py, or the prune methods would by default save the imp_score.npz along the checkpoint. :D
